Cleanup 20230923
Dynatrace/monitoring-coverage pull request #11
Opened 2023-09-23 11:04 UTC by LucasHocker

- Fix typo 
- Apply upstream updates
- Apply requested change from ADES-3542

2023-10-24 12:48 UTC, ffriedl89 requested changes
Only minor topics, overall the changeset looks good :)

2023-10-24 12:48 UTC, ffriedl89 commented on src/app/components/modals/InstallOneAgentModal.tsx
> +  const attentionLabel = (text: string) => {
Separate this into a standalone component. 
```
const AttentionLabel = (props: AttenionLabelProps) => {
  const { text } = props; 
  ...
}
```

2024-03-02 12:36 UTC, LucasHocker commented
@stefankoegl FYI this PR was pending approval for 5 months after requested changes were made.

2024-03-04 15:17 UTC, ffriedl89 approved these changes
The changes related to my requested changes look good to me.

2024-03-04 15:20 UTC, merged